### ISSUE TITLE
Animaciónes

### ISSUE THREAD

**Issue by Tomasvii** [paoguzmanok/mercado-liebre#4]
Los productos no poseen animaciónes.

**Comment by Tomasvii** [comment]
Poseen un hover en la resolución desktop, más no en la de tablet, ni animación.

**Comment by paoguzmanok** [comment]
No comprendo a que animacion se refiere, cuado dice que los productos no poseen animacion. 

.Tenia entendido que los hover eran a partir de laptop, ya que en resoluciones mas pequeñas no hay mouse para pasar.
