### ISSUE TITLE
Observaciónes

### ISSUE THREAD

**Issue by Tomasvii** [paoguzmanok/mercado-liebre#6]
Como recomendación, no implementaria el bold, o negrita, que poseen los textos en toda la página. Tambíen centraria el copyright, ya que todo el resto de contenido está centrado.
![imagen](https://user-images.githubusercontent.com/106355821/210668854-3e97ee57-d7f2-4b25-8096-f7c93ae767f1.png)

En los formularios, el footer no llega a ocupar todo el ancho, y el copy quedó afuera
![imagen](https://user-images.githubusercontent.com/106355821/210670690-c56d5e1b-bb72-4123-b0f3-a4969ede63e6.png)
Sugeriria, cuando vas a reutilizar un footer y header, directamente (una vez ya terminados), copiarlos y pegarlos en los html correspondientes.

**Comment by paoguzmanok** [comment]
Muchas gracias!! tomo y aplico todas las sugerencias.
